# -*- coding: utf-8 -*-
"""
Code Challenge savollar banki — boshlang'ich daraja.

Har bir savol: mavzu (html/css/js/python/algo), daraja (0 oson, 1 o'rta,
2 qiyin), matn, variantlar, to'g'ri javob indeksi, tushuntirish.
`...` ichidagi matn frontendda kod shriftida ko'rsatiladi.
"""

QUESTIONS = (
    # ── HTML ──
    {'topic': 'html', 'level': 0, 'q': 'HTML nimaning qisqartmasi?',
     'options': ['HyperText Markup Language', 'High Text Machine Language', 'Hyper Tool Markup Language', 'Home Text Making Language'],
     'answer': 0, 'explain': "HTML — HyperText Markup Language, ya'ni gipermatnli belgilash tili. U veb-sahifaning tuzilishini yozadi."},
    {'topic': 'html', 'level': 0, 'q': "Veb-sahifadagi eng katta (eng muhim) sarlavha qaysi teg bilan yoziladi?",
     'options': ['`<h1>`', '`<h6>`', '`<head>`', '`<title>`'],
     'answer': 0, 'explain': "`<h1>` — eng muhim sarlavha, `<h6>` — eng kichigi. `<title>` esa brauzer yorlig'idagi nom."},
    {'topic': 'html', 'level': 0, 'q': 'Havola (link) qaysi teg bilan yaratiladi?',
     'options': ['`<a>`', '`<link>`', '`<href>`', '`<url>`'],
     'answer': 0, 'explain': '`<a href="...">matn</a>` — havola. `<link>` esa CSS kabi tashqi fayllarni ulaydi.'},
    {'topic': 'html', 'level': 0, 'q': "Sahifaga rasm qo'shish uchun qaysi teg ishlatiladi?",
     'options': ['`<img>`', '`<image>`', '`<src>`', '`<pic>`'],
     'answer': 0, 'explain': '`<img src="rasm.png" alt="tavsif">` — rasm qo\'shadi.'},
    {'topic': 'html', 'level': 0, 'q': "Raqamlangan (tartiblangan) ro'yxat qaysi teg bilan yoziladi?",
     'options': ['`<ol>`', '`<ul>`', '`<li>`', '`<list>`'],
     'answer': 0, 'explain': "`<ol>` — raqamlangan, `<ul>` — belgili ro'yxat. Har bir band `<li>` ichida yoziladi."},
    {'topic': 'html', 'level': 1, 'q': '`<img>` tegida rasm manzili qaysi atributda yoziladi?',
     'options': ['`src`', '`href`', '`alt`', '`link`'],
     'answer': 0, 'explain': '`src` — rasm manzili. `alt` — rasm ko\'rinmasa chiqadigan matnli tavsif.'},
    {'topic': 'html', 'level': 1, 'q': '`alt` atributi nima uchun kerak?',
     'options': ["Rasm ko'rinmasa yoki ekran o'quvchi uchun matnli tavsif", "Rasm o'lchamini belgilaydi", "Rasmni markazga qo'yadi", "Rasmga havola qo'shadi"],
     'answer': 0, 'explain': "`alt` ko'zi ojiz foydalanuvchilarning ekran o'quvchisi uchun va rasm yuklanmaganda ko'rinadi."},
    {'topic': 'html', 'level': 1, 'q': "Formada foydalanuvchi matn kiritadigan maydon qaysi teg?",
     'options': ['`<input>`', '`<form>`', '`<button>`', '`<label>`'],
     'answer': 0, 'explain': '`<input type="text">` — matn kiritish maydoni. `<form>` — butun forma, `<label>` — maydon nomi.'},
    {'topic': 'html', 'level': 2, 'q': "Qaysi teg semantik (ma'noli) teg hisoblanadi?",
     'options': ['`<article>`', '`<div>`', '`<span>`', '`<b>`'],
     'answer': 0, 'explain': "`<article>`, `<header>`, `<nav>`, `<footer>` kabi teglar mazmunni bildiradi. `<div>` va `<span>` esa ma'nosiz konteynerlar."},
    {'topic': 'html', 'level': 2, 'q': '`<meta name="viewport">` nima uchun kerak?',
     'options': ["Sahifani mobil qurilmalarda to'g'ri masshtablash uchun", "Sahifa sarlavhasini o'zgartirish uchun", 'Rasmlarni tez yuklash uchun', 'CSS faylni ulash uchun'],
     'answer': 0, 'explain': "viewport meta tegi bo'lmasa, telefon sahifani kichraytirib ko'rsatadi — responsive dizayn uchun zarur."},

    # ── CSS ──
    {'topic': 'css', 'level': 0, 'q': "Matn rangini qaysi xususiyat o'zgartiradi?",
     'options': ['`color`', '`background-color`', '`font-color`', '`text-color`'],
     'answer': 0, 'explain': '`color: red;` — matn rangi. `background-color` — fon rangi.'},
    {'topic': 'css', 'level': 0, 'q': "Element fonini (orqa rangini) o'zgartirish uchun qaysi xususiyat ishlatiladi?",
     'options': ['`background-color`', '`color`', '`bgcolor`', '`fill`'],
     'answer': 0, 'explain': '`background-color: #eee;` — element foni.'},
    {'topic': 'css', 'level': 0, 'q': 'CSS\'da class selektori qanday yoziladi?',
     'options': ['`.menu`', '`#menu`', '`menu`', '`*menu`'],
     'answer': 0, 'explain': 'Nuqta (`.menu`) — class, panjara (`#menu`) — id, belgisiz (`menu`) — teg nomi.'},
    {'topic': 'css', 'level': 0, 'q': 'Matnni qalin qilish uchun qaysi qoida to\'g\'ri?',
     'options': ['`font-weight: bold;`', '`font-style: bold;`', '`text-weight: bold;`', '`font: thick;`'],
     'answer': 0, 'explain': "`font-weight` — qalinlik, `font-style` esa qiya (italic) yozuv uchun."},
    {'topic': 'css', 'level': 1, 'q': 'id selektori qanday yoziladi?',
     'options': ['`#header`', '`.header`', '`@header`', '`&header`'],
     'answer': 0, 'explain': 'id — `#` bilan: `#header { ... }`. Sahifada bitta id faqat bir marta ishlatiladi.'},
    {'topic': 'css', 'level': 1, 'q': "Matnni markazga tekislash uchun qaysi qoida ishlatiladi?",
     'options': ['`text-align: center;`', '`align: center;`', '`text-center: yes;`', '`center: text;`'],
     'answer': 0, 'explain': '`text-align` — matnni chapga, o\'ngga yoki markazga tekislaydi.'},
    {'topic': 'css', 'level': 1, 'q': "Elementlarni bir qatorga moslashuvchan joylashtirish uchun qaysi qiymat qulay?",
     'options': ['`display: flex;`', '`display: none;`', '`position: static;`', '`float: none;`'],
     'answer': 0, 'explain': 'Flexbox (`display: flex`) elementlarni qator yoki ustun bo\'ylab oson joylashtiradi.'},
    {'topic': 'css', 'level': 1, 'q': '`margin` va `padding` farqi nimada?',
     'options': ["margin — element tashqarisidagi, padding — ichkarisidagi bo'shliq", 'Ikkalasi bir xil', "margin — ichkaridagi, padding — tashqaridagi bo'shliq", 'padding faqat matn uchun ishlaydi'],
     'answer': 0, 'explain': "padding — chegara ichidagi, margin — chegaradan tashqaridagi bo'shliq."},
    {'topic': 'css', 'level': 2, 'q': "Qaysi selektorning ustuvorligi (specificity) eng yuqori?",
     'options': ['`#menu`', '`.menu`', '`div`', '`*`'],
     'answer': 0, 'explain': "Ustuvorlik: id > class > teg > `*`. Shuning uchun `#menu` qoidasi ustun keladi."},
    {'topic': 'css', 'level': 2, 'q': '`@media` so\'rovi nima uchun ishlatiladi?',
     'options': ["Ekran o'lchamiga qarab turli uslub berish uchun", "Rasm qo'shish uchun", 'Shrift yuklash uchun', 'Animatsiya yaratish uchun'],
     'answer': 0, 'explain': "`@media (max-width: 600px) { ... }` — telefon kabi kichik ekranlar uchun alohida uslub (responsive)."},

    # ── JavaScript ──
    {'topic': 'js', 'level': 0, 'q': "Qayta tayinlanmaydigan (o'zgarmas) o'zgaruvchi qaysi kalit so'z bilan e'lon qilinadi?",
     'options': ['`const`', '`let`', '`var`', '`static`'],
     'answer': 0, 'explain': "`const` — qiymati qayta tayinlanmaydi. `let` bilan e'lon qilingan o'zgaruvchini o'zgartirish mumkin."},
    {'topic': 'js', 'level': 0, 'q': '`console.log(2 + 3)` nima chiqaradi?',
     'options': ['`5`', '`23`', '`"2 + 3"`', 'Xato beradi'],
     'answer': 0, 'explain': 'Ikkala qiymat ham son — oddiy qo\'shish: 2 + 3 = 5.'},
    {'topic': 'js', 'level': 0, 'q': "JavaScript'da funksiya qaysi kalit so'z bilan e'lon qilinadi?",
     'options': ['`function`', '`def`', '`func`', '`method`'],
     'answer': 0, 'explain': "`function salom() { ... }` — funksiya e'loni. `def` — Python'da ishlatiladi."},
    {'topic': 'js', 'level': 1, 'q': "`console.log('2' + 3)` nima chiqaradi?",
     'options': ['`"23"`', '`5`', '`6`', 'Xato beradi'],
     'answer': 0, 'explain': "Biri matn (string) bo'lsa, `+` ularni ulaydi: '2' + 3 = '23'."},
    {'topic': 'js', 'level': 1, 'q': 'Massiv uzunligi qanday topiladi?',
     'options': ['`arr.length`', '`arr.size()`', '`length(arr)`', '`arr.count`'],
     'answer': 0, 'explain': "`length` — xususiyat (qavssiz): `[1, 2, 3].length` → 3."},
    {'topic': 'js', 'level': 1, 'q': '`===` operatori nimani tekshiradi?',
     'options': ['Qiymat va turini', 'Faqat qiymatni', 'Faqat turini', 'Qiymat tayinlaydi'],
     'answer': 0, 'explain': "`===` qat'iy tenglik: `5 === '5'` → false, chunki turlari har xil."},
    {'topic': 'js', 'level': 1, 'q': "Massiv oxiriga element qo'shish metodi qaysi?",
     'options': ['`push()`', '`pop()`', '`shift()`', '`slice()`'],
     'answer': 0, 'explain': "`push()` — oxiriga qo'shadi, `pop()` — oxiridagini olib tashlaydi."},
    {'topic': 'js', 'level': 2, 'q': '`typeof null` natijasi nima?',
     'options': ['`"object"`', '`"null"`', '`"undefined"`', '`"number"`'],
     'answer': 0, 'explain': 'Bu JavaScript\'ning tarixiy xususiyati: `typeof null` → "object".'},
    {'topic': 'js', 'level': 2, 'q': '`[1, 2, 3].map(x => x * 2)` natijasi nima?',
     'options': ['`[2, 4, 6]`', '`[1, 2, 3, 2]`', '`12`', '`[3, 4, 5]`'],
     'answer': 0, 'explain': "`map` har bir elementga funksiyani qo'llab, yangi massiv qaytaradi."},
    {'topic': 'js', 'level': 2, 'q': '`let a = 5; a += 3;` dan keyin `a` ning qiymati nechchi?',
     'options': ['`8`', '`53`', '`5`', '`3`'],
     'answer': 0, 'explain': '`a += 3` — bu `a = a + 3` ning qisqa yozuvi: 5 + 3 = 8.'},

    # ── Python ──
    {'topic': 'python', 'level': 0, 'q': "Python'da ekranga matn chiqaradigan funksiya qaysi?",
     'options': ['`print()`', '`echo()`', '`console.log()`', '`write()`'],
     'answer': 0, 'explain': '`print("Salom")` — ekranga chiqaradi.'},
    {'topic': 'python', 'level': 0, 'q': "Python'da izoh (kommentariya) qaysi belgi bilan boshlanadi?",
     'options': ['`#`', '`//`', '`<!--`', '`--`'],
     'answer': 0, 'explain': '`# bu izoh` — Python bu qatorni bajarmaydi. `//` esa JavaScript\'da.'},
    {'topic': 'python', 'level': 0, 'q': "Python'da funksiya qaysi kalit so'z bilan e'lon qilinadi?",
     'options': ['`def`', '`function`', '`fun`', '`define`'],
     'answer': 0, 'explain': '`def salom():` — Python\'da funksiya e\'loni.'},
    {'topic': 'python', 'level': 1, 'q': "`len('salom')` natijasi nechchi?",
     'options': ['`5`', '`4`', '`6`', "`'salom'`"],
     'answer': 0, 'explain': "`len()` — uzunlik: 's', 'a', 'l', 'o', 'm' — 5 ta belgi."},
    {'topic': 'python', 'level': 1, 'q': '`7 // 2` natijasi nechchi?',
     'options': ['`3`', '`3.5`', '`4`', '`1`'],
     'answer': 0, 'explain': "`//` — butun bo'lish: 7 ni 2 ga bo'lganda butun qismi 3."},
    {'topic': 'python', 'level': 1, 'q': '`7 % 3` natijasi nechchi?',
     'options': ['`1`', '`2`', '`2.33`', '`21`'],
     'answer': 0, 'explain': "`%` — qoldiq: 7 = 3 × 2 + 1, qoldiq 1."},
    {'topic': 'python', 'level': 1, 'q': "Ro'yxat oxiriga element qo'shish metodi qaysi?",
     'options': ['`append()`', '`push()`', '`add()`', '`insertEnd()`'],
     'answer': 0, 'explain': "`sonlar.append(5)` — ro'yxat oxiriga qo'shadi. `push()` — JavaScript'da."},
    {'topic': 'python', 'level': 2, 'q': '`range(1, 5)` qaysi sonlarni beradi?',
     'options': ['1, 2, 3, 4', '1, 2, 3, 4, 5', '0, 1, 2, 3, 4', '2, 3, 4, 5'],
     'answer': 0, 'explain': "`range(a, b)` — a dan boshlab b gacha (b kirmaydi)."},
    {'topic': 'python', 'level': 2, 'q': '`[1, 2, 3][-1]` natijasi nima?',
     'options': ['`3`', '`1`', 'Xato beradi', '`-1`'],
     'answer': 0, 'explain': "Manfiy indeks oxiridan sanaydi: -1 — oxirgi element."},
    {'topic': 'python', 'level': 2, 'q': '`2 ** 3` natijasi nechchi?',
     'options': ['`8`', '`6`', '`9`', '`5`'],
     'answer': 0, 'explain': "`**` — darajaga ko'tarish: 2³ = 2 × 2 × 2 = 8."},

    # ── Algoritmlar ──
    {'topic': 'algo', 'level': 0, 'q': 'Algoritm nima?',
     'options': ["Masalani yechish uchun aniq qadamlar ketma-ketligi", 'Kompyuter qurilmasi', 'Dasturlash tili', 'Internet sahifasi'],
     'answer': 0, 'explain': "Algoritm — maqsadga olib boradigan aniq, tartiblangan qadamlar."},
    {'topic': 'algo', 'level': 0, 'q': "Blok-sxemada romb (◇) shakli nimani bildiradi?",
     'options': ['Shart (tekshirish)', 'Boshlanish', 'Hisoblash', 'Natijani chiqarish'],
     'answer': 0, 'explain': "Romb — shart: \"ha\" yoki \"yo'q\" yo'liga bo'linadi. Oval — boshlanish/tugash, to'rtburchak — amal."},
    {'topic': 'algo', 'level': 0, 'q': "Qaysi biri algoritmning xossasi EMAS?",
     'options': ['Noaniqlik', 'Aniqlik', 'Natijaviylik', 'Diskretlik'],
     'answer': 0, 'explain': "Algoritm xossalari: diskretlik, aniqlik, tushunarlilik, natijaviylik, ommaviylik. Noaniqlik — aksincha."},
    {'topic': 'algo', 'level': 1, 'q': 'Sikl (takrorlash) nima uchun ishlatiladi?',
     'options': ['Amallarni bir necha marta takrorlash uchun', "Dasturni to'xtatish uchun", "O'zgaruvchi e'lon qilish uchun", 'Izoh yozish uchun'],
     'answer': 0, 'explain': "`for` va `while` sikllari bir xil amallarni ko'p marta bajaradi."},
    {'topic': 'algo', 'level': 1, 'q': "Tartiblangan ro'yxatda qidirishning eng tez usuli qaysi?",
     'options': ['Ikkilik (binar) qidiruv', 'Ketma-ket qidiruv', 'Tasodifiy qidiruv', 'Teskari qidiruv'],
     'answer': 0, 'explain': "Binar qidiruv har qadamda qidiruv sohasini ikkiga bo'ladi — juda tez."},
    {'topic': 'algo', 'level': 1, 'q': 'Binar qidiruv har qadamda qidiruv sohasini qanday o\'zgartiradi?',
     'options': ['Ikki baravar kamaytiradi', 'Bittaga kamaytiradi', 'Ikki baravar oshiradi', "O'zgartirmaydi"],
     'answer': 0, 'explain': "O'rtadagi element bilan solishtirib, ro'yxatning keraksiz yarmi tashlab yuboriladi."},
    {'topic': 'algo', 'level': 1, 'q': 'Rekursiya nima?',
     'options': ["Funksiyaning o'zini o'zi chaqirishi", 'Sikl turi', "Ma'lumot turi", 'Xatolik turi'],
     'answer': 0, 'explain': "Masalan, faktorial: n! = n × (n−1)! — funksiya o'zini kichikroq son bilan chaqiradi."},
    {'topic': 'algo', 'level': 2, 'q': "Pufakcha (bubble sort) saralashda nima qilinadi?",
     'options': ["Qo'shni elementlar solishtirilib, kerak bo'lsa o'rni almashtiriladi", "Ro'yxat ikkiga bo'linadi", "Eng katta element o'chiriladi", 'Elementlar tasodifiy aralashtiriladi'],
     'answer': 0, 'explain': "Har o'tishda katta elementlar pufakchadek oxiriga \"suzib\" chiqadi."},
    {'topic': 'algo', 'level': 2, 'q': "n ta elementli massivda eng katta sonni topish uchun kamida nechta solishtirish kerak?",
     'options': ['n − 1', 'n', 'n / 2', '1'],
     'answer': 0, 'explain': "Birinchi elementni eng katta deb olib, qolgan n − 1 ta element bilan bittadan solishtiriladi."},
    {'topic': 'algo', 'level': 2, 'q': "Ikki sonning EKUBini topishning mashhur algoritmi qaysi?",
     'options': ['Evklid algoritmi', 'Dijkstra algoritmi', 'Pufakcha saralash', 'Binar qidiruv'],
     'answer': 0, 'explain': "Evklid algoritmi: EKUB(a, b) = EKUB(b, a mod b), qoldiq 0 bo'lguncha."},
)
